# docker-compose.production.yml
version: '3'

volumes:
  postgres_data_production:
  static_volume:
  foodgram_media:
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_data_production:/var/lib/postgresql/data
  backend:
    image: kolbacyn/foodgram_backend:1.1.14
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - foodgram_media:/app/media/
  frontend:
    image: kolbacyn/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: kolbacyn/foodgram_gateway:1.1.2
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - foodgram_media:/media/
    ports:
      - 8100:80
