version: '3.3'
volumes:
  postgres_data:
  foodgram_static:
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    image: foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - foodgram_static:/backend_static
  frontend:
    image: foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - foodgram_static:/frontend_static
  gateway:
    image: foodgram_gateway
    volumes:
      - foodgram_static:/staticfiles/
    ports:
      - 8100:80
