# Generated by Django 3.2 on 2023-08-28 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230828_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientrelation',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_of_ingredients', to='recipes.ingredient', verbose_name='Связаный ингредиент'),
        ),
    ]
