# Generated by Django 3.2 on 2023-08-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230826_1031'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredientrelation',
            name='unique_ingredient_recipe',
        ),
        migrations.RenameField(
            model_name='recipeingredientrelation',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.AddConstraint(
            model_name='recipeingredientrelation',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_ingredient_recipe'),
        ),
    ]
