# Generated by Django 3.2 on 2023-08-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230826_1049'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredientrelation',
            name='unique_ingredient_recipe',
        ),
        migrations.RenameField(
            model_name='recipeingredientrelation',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.AddConstraint(
            model_name='recipeingredientrelation',
            constraint=models.UniqueConstraint(fields=('ingredients', 'recipe'), name='unique_ingredient_recipe'),
        ),
    ]
