# Generated by Django 3.2 on 2023-08-28 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_ingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientrelation',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_recipe', to='recipes.recipe', verbose_name='Связаный рецепт'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredientrelation',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_ingredient_recipe'),
        ),
    ]
