# Generated by Django 3.2 on 2023-08-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230827_0955'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='prevent_repitative_favorites',
        ),
    ]
