# Generated by Django 3.2 on 2023-08-26 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230826_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Минимальное время приготовления = 0')], verbose_name='Время приготовления'),
        ),
    ]
